import type { Metadata } from "next";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { PageHero } from "@/components/PageHero";
import { RelatedLinks } from "@/components/RelatedLinks";

export const metadata: Metadata = { title: "Editorial Policy", description: "The Dog Bond content standards for people-first information, humane training, public safety, and responsible partnerships." };
const principles = ["People-first dog ownership information", "African context matters", "Humane training standard", "Public safety standard", "No medical diagnosis", "No reckless aggression content", "Expert review pathway coming later", "Corrections and updates", "Partner independence"];
export default function EditorialPolicyPage() { return <main><Header /><PageHero eyebrow="Trust standard" title="Editorial Policy" text="The Dog Bond publishes dog ownership information around responsibility, humane care, African household reality, and public safety." /><section className="bg-white px-5 py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-3">{principles.map((item) => <div key={item} className="rounded-[2rem] border border-earth-200 bg-earth-50 p-6 shadow-card"><h2 className="font-display text-2xl font-semibold text-earth-950">{item}</h2><p className="mt-3 text-sm leading-7 text-earth-700">Our editorial judgment puts responsible ownership before status, clicks, fear, or reckless promotion.</p></div>)}</div><div className="mx-auto mt-10 max-w-5xl rounded-[2rem] bg-earth-950 p-8 text-earth-50"><p className="text-lg leading-8">The Dog Bond may later work with trainers, vets, shelters, breeders, and dog-care brands, but responsible ownership remains the editorial center.</p></div></section><RelatedLinks links={[{ title: "Disclaimer", href: "/disclaimer", text: "Understand the limits of the platform." }, { title: "Partner With Us", href: "/partner-with-us", text: "See future partnership principles." }, { title: "Contact", href: "/contact", text: "Send corrections or feedback." }]} /><Footer /></main>; }
